spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: chirp@sandbox0d165fc7e8994be58a7aab95f7395611.mailgun.org
jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true
chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    apply-limit: true
  web-socket:
    allowed-origins: "http://chirp.gideon.com"